spring.application.name=PetAdoptionBatch

# Pet DataSource
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.pet.jdbc-url=jdbc:mysql://localhost:3306/local
spring.datasource.pet.username=root
spring.datasource.pet.password=test1234

# Batch DataSource
spring.datasource.batch.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.batch.jdbc-url=jdbc:mysql://localhost:3306/local2
spring.datasource.batch.username=root
spring.datasource.batch.password=test1234

# Batch properties
batch.pet.file-manager.filepath=C:\\Users\\Surface Laptop Go\\IdeaProjects\\src
batch.pet.file-manager.chucksize=10
